version: '3.8'

services:
  backend:
    build: ./backend/app/app
    container_name: fastapi-backend
    env_file:
      - ./backend/app/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: josevalencar
      POSTGRES_PASSWORD: "@Vitjal1"
      POSTGRES_DB: insireadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  postgres_data: 