"""Add name column to users table

Revision ID: 8b9ea05751ad
Revises: 3c05ce8fb214
Create Date: 2025-06-17 11:11:30.194954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9ea05751ad'
down_revision: Union[str, None] = '3c05ce8fb214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.execute("UPDATE users SET name = 'Unknown' WHERE name IS NULL")
    op.alter_column('users', 'name', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
